package aula1;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

public class UsuarioView extends javax.swing.JFrame {

    private String estado = "navegacao";
    private String codigo;
    ArrayList<String> usuarios = new ArrayList<>();
    ArrayList<String> categorias = new ArrayList<>();

    public UsuarioView() {
        usuarios = Controle.ControleUsuario.SelecionarTudo();
        categorias = Controle.ControleCategoria.SelecionarTudo();

        initComponents();

        AtivarInsercao(false);
        CarregarTabela();
    }

    private void CarregarTabela() {
        for (String usuario : usuarios) {
            InserirGrade(usuario);
        }
    }

    private void InserirGrade(String dados) {
        DefaultTableModel modelo = (DefaultTableModel) tabelausuario.getModel();
        JSONObject jsonobj = new JSONObject(dados);
        

        String[] teste = new String[4];
        teste[0] = Integer.toString(jsonobj.getInt("codigo"));
        teste[1] = jsonobj.getString("nome");
        teste[2] = jsonobj.getString("login");
        teste[3] = jsonobj.getString("senha");

        modelo.addRow(teste);
    }

    private void InserirGradeInsercao() {
        usuarios = Controle.ControleUsuario.SelecionarTudo();
        CarregarTabela();
    }

    public void limpar() {
        codigousuario.setText("");
        nomeusuario.setText("");
        loginusuario.setText("");
        senhausuario.setText("");
    }

    private void AtivarInsercao(boolean estado) {

        //Controlador de botões
        botaonovo.setEnabled(!estado);
        botaogravar.setEnabled(estado);
        botaocancelar.setEnabled(estado);
        botaoeditar.setEnabled(!estado);
        botaoexcluir.setEnabled(!estado);

        AtivarInsercao2(estado);
    }

    private void AtivarInsercao2(boolean estado) {

        //Controlador de inserção
        codigousuario.setEditable(/*!estado*/false);
        nomeusuario.setEditable(estado);
        loginusuario.setEditable(estado);
        senhausuario.setEditable(estado);
    }

    private void EditarGrade(String[] dados) {
        int iLinha = tabelausuario.getSelectedRow();

        DefaultTableModel modelo = (DefaultTableModel) tabelausuario.getModel();
        modelo.setValueAt(dados[0], iLinha, 0);
        modelo.setValueAt(dados[1], iLinha, 1);
        modelo.setValueAt(dados[2], iLinha, 2);
        modelo.setValueAt(dados[3], iLinha, 3);
    }

    private void RemoverDaGrade() {
        int iLinha = tabelausuario.getSelectedRow();

        DefaultTableModel modelo = (DefaultTableModel) tabelausuario.getModel();
        modelo.removeRow(iLinha);
    }

    private void Gravar() {
        String dados[] = new String[4];
        JSONObject json = new JSONObject();
        if (estado.equals("INSERT")) {
            json.put("codigo", "0");
            json.put("nome", nomeusuario.getText());
            json.put("login", loginusuario.getText());
            json.put("senha", senhausuario.getText());
            json.put("categoria", categoriacombo.getSelectedIndex() + 1);
            //System.out.println(categoriacombo.getSelectedIndex());
            String strJson = json.toString();
            Controle.ControleUsuario.Salvar(strJson);

            //InserirGrade(strJson);
            InserirGradeInsercao();
        } else {
            if (estado.equals("UPDATE")) {
                json.put("codigo", codigousuario.getText());
                json.put("nome", nomeusuario.getText());
                json.put("login", loginusuario.getText());
                json.put("senha", senhausuario.getText());

                String strJson = json.toString();
                Controle.ControleUsuario.Salvar(strJson);
                InserirGradeInsercao();
            } else if (estado.equals("DELETE")) {
                Controle.ControleUsuario.Deletar(dados[0]);
                RemoverDaGrade();

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigousuario = new javax.swing.JTextField();
        nomeusuario = new javax.swing.JTextField();
        loginusuario = new javax.swing.JTextField();
        botaonovo = new javax.swing.JButton();
        botaoeditar = new javax.swing.JButton();
        botaoexcluir = new javax.swing.JButton();
        botaocancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelausuario = new javax.swing.JTable();
        senhausuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaogravar = new javax.swing.JButton();
        categoriacombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuário");

        jLabel2.setText("Nome");

        jLabel3.setText("Código");

        jLabel4.setText("Login");

        botaonovo.setText("Novo");
        botaonovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaonovoActionPerformed(evt);
            }
        });

        botaoeditar.setText("Editar");
        botaoeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoeditarActionPerformed(evt);
            }
        });

        botaoexcluir.setText("Excluir");
        botaoexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoexcluirActionPerformed(evt);
            }
        });

        botaocancelar.setText("Cancelar");
        botaocancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocancelarActionPerformed(evt);
            }
        });

        tabelausuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelausuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelausuario);

        jLabel5.setText("Senha");

        botaogravar.setText("Gravar");
        botaogravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaogravarActionPerformed(evt);
            }
        });

        categoriacombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriacomboActionPerformed(evt);
            }
        });

        jLabel6.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botaonovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaogravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoeditar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(botaocancelar)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(nomeusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(codigousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(senhausuario, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(categoriacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loginusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhausuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaonovo)
                    .addComponent(botaoeditar)
                    .addComponent(botaoexcluir)
                    .addComponent(botaocancelar)
                    .addComponent(botaogravar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaogravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaogravarActionPerformed
        // TODO add your handling code here:
        Gravar();
        limpar();
        estado = "navegacao";
        AtivarInsercao(false);
    }//GEN-LAST:event_botaogravarActionPerformed

    private void botaonovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaonovoActionPerformed
        // TODO add your handling code here:
        limpar();
        estado = "INSERT";
        AtivarInsercao(true);
        nomeusuario.requestFocus();
    }//GEN-LAST:event_botaonovoActionPerformed

    private void botaoexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoexcluirActionPerformed
        // TODO add your handling code here:
        estado = "DELETE";
        int iLinha = tabelausuario.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tabelausuario.getModel();
        codigo = (String) modelo.getValueAt(iLinha, 0);
        codigousuario.setText(codigo);
        Controle.ControleUsuario.Deletar(codigo);
        RemoverDaGrade();
        AtivarInsercao(true);
    }//GEN-LAST:event_botaoexcluirActionPerformed

    private void botaocancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocancelarActionPerformed
        // TODO add your handling code here:
        limpar();
        estado = "navegacao";
        AtivarInsercao(false);
    }//GEN-LAST:event_botaocancelarActionPerformed

    private void botaoeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoeditarActionPerformed
        // TODO add your handling code here:
        estado = "UPDATE";
        AtivarInsercao(true);
    }//GEN-LAST:event_botaoeditarActionPerformed

    private void tabelausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelausuarioMouseClicked
        // TODO add your handling code here:
        int iLinha = tabelausuario.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tabelausuario.getModel();

        String codigo = (String) modelo.getValueAt(iLinha, 0);
        String nome = (String) modelo.getValueAt(iLinha, 1);
        String login = (String) modelo.getValueAt(iLinha, 2);
        String senha = (String) modelo.getValueAt(iLinha, 3);

        codigousuario.setText(codigo);
        nomeusuario.setText(nome);
        loginusuario.setText(login);
        senhausuario.setText(senha);

    }//GEN-LAST:event_tabelausuarioMouseClicked

    private void categoriacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriacomboActionPerformed
        // TODO add your handling code here:
        for (String categoria : categorias) {
            JSONObject jsonobj = new JSONObject(categoria);
            //categoriacombo.removeAllItems();
            categoriacombo.addItem(jsonobj.getString("descricao"));
            //categoriacombo.addItem("1");
            System.out.println(categoriacombo);
        }
    }//GEN-LAST:event_categoriacomboActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        for (String categoria : categorias) {
            JSONObject jsonobj = new JSONObject(categoria);
            categoriacombo.removeAllItems();
            categoriacombo.addItem(jsonobj.getString("descricao"));
            //categoriacombo.addItem("1");
            System.out.println(categoriacombo);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaocancelar;
    private javax.swing.JButton botaoeditar;
    private javax.swing.JButton botaoexcluir;
    private javax.swing.JButton botaogravar;
    private javax.swing.JButton botaonovo;
    private javax.swing.JComboBox categoriacombo;
    private javax.swing.JTextField codigousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loginusuario;
    private javax.swing.JTextField nomeusuario;
    private javax.swing.JTextField senhausuario;
    private javax.swing.JTable tabelausuario;
    // End of variables declaration//GEN-END:variables
}
